### ISSUE TITLE
execvp(): Not a directory

### ISSUE THREAD

**Issue by andrewhilts** [bengourley/placeholder#1]
Trying to run this on my mac, and when requesting an image, the node server prints:

execvp(): Not a directory
GET /500x300 200 6ms

No image is displayed in the browser at http://0.0.0.0:9999/500x300, however

**Comment by bengourley** [comment]
Sounds like something's up with your gm install. Did you `brew install graphicsmagick`?

**Comment by andrewhilts** [comment]
You're right. The brew link failed, so I had to do it manually, and reinstall. Now it's working, except for when I want text. In that case, I get a Ghostscript error: gm convert: Unable to read font (/usr/local/share/ghostscript/fonts/n019003l.pfb) [No such file or directory].

**Comment by bengourley** [comment]
Bummer. Yeah these native deps are a pain. Try brewing ghostscript?
